const Data = [
  {
    id: "1",
    name: "day-01-in-30-days-of-react",
    link: "https://github.com/nogw/day-01-in-30-days-of-react",
    image: 'https://raw.githubusercontent.com/nogw/day-01-in-30-days-of-react/master/site.png',
  },
  {
    id: "2",
    name: "day-02-in-30-days-of-react",
    link: "https://github.com/nogw/day-02-in-30-days-of-react",
    image: 'https://raw.githubusercontent.com/nogw/day-02-in-30-days-of-react/master/site.png',
  },
  {
    id: "3",
    name: "day-03-in-30-days-of-react",
    link: "https://github.com/nogw/day-03-in-30-days-of-react",
    image: 'https://raw.githubusercontent.com/nogw/day-03-in-30-days-of-react/master/site.png',
  },
  {
    id: "4",
    name: "day-04-in-30-days-of-react",
    link: "https://github.com/nogw/day-04-in-30-days-of-react",
    image: 'https://raw.githubusercontent.com/nogw/day-04-in-30-days-of-react/master/site.png',
  },
  {
    id: "5",
    name: "day-05-in-30-days-of-react",
    link: "https://github.com/nogw/day-05-in-30-days-of-react",
    image: 'https://raw.githubusercontent.com/nogw/day-05-in-30-days-of-react/master/site.png',
  },
  {
    id: "6",
    name: "day-06-in-30-days-of-react",
    link: "https://github.com/nogw/day-06-in-30-days-of-react",
    image: 'https://raw.githubusercontent.com/nogw/day-06-in-30-days-of-react/master/site.png',
  },
  {
    id: "7",
    name: "day-07-in-30-days-of-react",
    link: "https://github.com/nogw/day-07-in-30-days-of-react",
    image: 'https://raw.githubusercontent.com/nogw/day-07-in-30-days-of-react/master/site.png',
  },
  {
    id: "8",
    name: "day-08-in-30-days-of-react",
    link: "https://github.com/nogw/day-08-in-30-days-of-react",
    image: 'https://raw.githubusercontent.com/nogw/day-08-in-30-days-of-react/master/site.png',
  },
  {
    id: "9",
    name: "day-09-in-30-days-of-react",
    link: "https://github.com/nogw/day-09-in-30-days-of-react",
    image: 'https://raw.githubusercontent.com/nogw/day-09-in-30-days-of-react/master/site.png',
  },
  {
    id: "10",
    name: "day-10-in-30-days-of-react",
    link: "https://github.com/nogw/day-10-in-30-days-of-react",
    image: 'https://raw.githubusercontent.com/nogw/day-10-in-30-days-of-react/master/site.png',
  },
  {
    id: "11",
    name: "day-11-in-30-days-of-react",
    link: "https://github.com/nogw/day-11-in-30-days-of-react",
    image: 'https://raw.githubusercontent.com/nogw/day-11-in-30-days-of-react/master/site.png',
  },
  {
    id: "12",
    name: "day-12-in-30-days-of-react",
    link: "https://github.com/nogw/day-12-in-30-days-of-react",
    image: 'https://raw.githubusercontent.com/nogw/day-12-in-30-days-of-react/master/site.png',
  },
  {
    id: "13",
    name: "day-13-in-30-days-of-react",
    link: "https://github.com/nogw/day-13-in-30-days-of-react",
    image: 'https://raw.githubusercontent.com/nogw/day-13-in-30-days-of-react/master/site.png',
  },
  {
    id: "14",
    name: "day-14-in-30-days-of-react",
    link: "https://github.com/nogw/day-14-in-30-days-of-react",
    image: 'https://raw.githubusercontent.com/nogw/day-14-in-30-days-of-react/master/site.png',
  },
  {
    id: "15",
    name: "day-15-in-30-days-of-react",
    link: "https://github.com/nogw/day-15-in-30-days-of-react",
    image: 'https://raw.githubusercontent.com/nogw/day-15-in-30-days-of-react/master/site.png',
  },
  {
    id: "16",
    name: "day-16-in-30-days-of-react",
    link: "https://github.com/nogw/day-16-in-30-days-of-react",
    image: 'https://raw.githubusercontent.com/nogw/day-16-in-30-days-of-react/master/site.png',
  },
  {
    id: "17",
    name: "day-17-in-30-days-of-react",
    link: "https://github.com/nogw/day-17-in-30-days-of-react",
    image: 'https://raw.githubusercontent.com/nogw/day-17-in-30-days-of-react/master/site.png',
  },
  {
    id: "18",
    name: "day-18-in-30-days-of-react",
    link: "https://github.com/nogw/day-18-in-30-days-of-react",
    image: 'https://raw.githubusercontent.com/nogw/day-18-in-30-days-of-react/master/site.png',
  },
  {
    id: "19",
    name: "day-19-in-30-days-of-react",
    link: "https://github.com/nogw/day-19-in-30-days-of-react",
    image: 'https://raw.githubusercontent.com/nogw/day-19-in-30-days-of-react/master/site.png',
  },
  {
    id: "20",
    name: "day-20-in-30-days-of-react",
    link: "https://github.com/nogw/day-20-in-30-days-of-react",
    image: 'https://raw.githubusercontent.com/nogw/day-20-in-30-days-of-react/master/site.png',
  },
  {
    id: "21",
    name: "day-21-in-30-days-of-react",
    link: "https://github.com/nogw/day-21-in-30-days-of-react",
    image: 'https://raw.githubusercontent.com/nogw/day-21-in-30-days-of-react/master/site.png',
  },
  {
    id: "22",
    name: "day-22-in-30-days-of-react",
    link: "https://github.com/nogw/day-22-in-30-days-of-react",
    image: 'https://raw.githubusercontent.com/nogw/day-22-in-30-days-of-react/master/site.png',
  },
  {
    id: "23",
    name: "day-23-in-30-days-of-react",
    link: "https://github.com/nogw/day-23-in-30-days-of-react",
    image: 'https://raw.githubusercontent.com/nogw/day-23-in-30-days-of-react/master/site.png',
  },
  {
    id: "24",
    name: "day-24-in-30-days-of-react",
    link: "https://github.com/nogw/day-24-in-30-days-of-react",
    image: 'https://raw.githubusercontent.com/nogw/day-24-in-30-days-of-react/master/site.png',
  },
  {
    id: "25",
    name: "day-25-in-30-days-of-react",
    link: "https://github.com/nogw/day-25-in-30-days-of-react",
    image: 'https://raw.githubusercontent.com/nogw/day-25-in-30-days-of-react/master/site.png',
  },
  {
    id: "26",
    name: "day-26-in-30-days-of-react",
    link: "https://github.com/nogw/day-26-in-30-days-of-react",
    image: 'https://raw.githubusercontent.com/nogw/day-26-in-30-days-of-react/master/site.png',
  },
  {
    id: "27",
    name: "day-27-in-30-days-of-react",
    link: "https://github.com/nogw/day-27-in-30-days-of-react",
    image: 'https://raw.githubusercontent.com/nogw/day-27-in-30-days-of-react/master/site.png',
  },
  {
    id: "28",
    name: "day-28-in-30-days-of-react",
    link: "https://github.com/nogw/day-28-in-30-days-of-react",
    image: 'https://raw.githubusercontent.com/nogw/day-28-in-30-days-of-react/master/site.png',
  },
  {
    id: "29",
    name: "day-29-in-30-days-of-react",
    link: "https://github.com/nogw/day-29-in-30-days-of-react",
    image: 'https://raw.githubusercontent.com/nogw/day-29-in-30-days-of-react/master/site.png',
  },
  {
    id: "30",
    name: "day-30-in-30-days-of-react",
    link: "https://github.com/nogw/day-30-in-30-days-of-react",
    image: 'https://raw.githubusercontent.com/nogw/day-30-in-30-days-of-react/master/site.png',
  }
]

export default Data